using UnityEngine;

namespace UnityTutorialSystem.Events
{
    /// <summary>
    ///    A base type for all MonoBehaviours that can activate EventStream messages.
    ///    StreamEventSources are referenced by the NextEvent-predictor system to
    ///    simplify the wiring up of event cascades. 
    /// </summary>
    public abstract class StreamEventSource : MonoBehaviour
    {
        /// <summary>
        ///   Checks whether the message given will be generated by is source. The
        ///   NextEventSelector implementations will use this method to locate components
        ///   that could trigger the event in question.
        /// </summary>
        /// <param name="msg">The message object to be evaluated</param>
        /// <returns>true if the source will generate this message, false otherwise.</returns>
        public abstract bool WillGenerateMessage(BasicEventStreamMessage msg);
    }
}